---
# http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-using-volumes.html
# https://help.ubuntu.com/14.04/serverguide/network-file-system.html
# see group_vars/vcl for datasets variable
- name: Install packages
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - nfs-kernel-server

- name: create block device mount points
  file: path={{ item.mount }} state=directory mode=0777
  with_items: datasets

- name: add to fstab
  lineinfile: dest=/etc/fstab line="{{ item.device }}  {{ item.mount }}  ext3  ro  0  0"
  with_items: datasets

- name: configure NFS server
  lineinfile: dest=/etc/exports line="{{ item.mount }}  *(ro,sync,no_root_squash)"
  with_items: datasets

- name: start NFS server
  service: name=nfs-kernel-server enabled=yes
